name: sigap_mobile
description: SIGAP Planner - Mobile technician (skeleton)
publish_to: "none"
version: 1.0.8+9
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.0.15
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  package_info_plus: ^4.0.0
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  uuid: ^3.0.7
  firebase_core: ^2.10.0
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^13.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true